import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Navbar from "@/components/Navbar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased h-screen`}
      >
        <Navbar></Navbar>
        {children}
        <footer>
          This is footer
        </footer>
      </body>
    </html>
  );
}
